### ISSUE TITLE
Invalid documentation link

### ISSUE THREAD

**Issue by lanzone1** [baldwin-agency/gtm-social-purchase-tag#1]
Hi,

We're reviewing, we noticed that the link to documentation https://github.com/baldwin-agency/gtm-social-purchase-tag/blob/main/README.md is not valid. Please update the link.

Otherwise, it looks good. Thanks.

**Comment by hostep** [comment]
Hi @lanzone1

I've added a branch `main` now (next to `master`) and made it the default one, now the link you mentioned works.

All good now?

**Comment by lanzone1** [comment]
Looks good. Thanks.
